### ISSUE TITLE
Fails to do stuff

### ISSUE THREAD

**Issue by ghost** [feross/eslint-config-standard-react#36]
I like to consider myself an <q>advanced</q> user. I installed this because it was mentioned in the standard docs and because I'm trying to make some React magic disappear from my linters. But after following the usage instructions, touching and configuring the lint config file and running this, absolutely nothing changes in my output. Which begs the question. Why does this even exist?

```
npm -v && node -v
3.10.3
v6.3.1
```

**Comment by feross** [comment]
This package is really only useful if you plan to use ESLint directly. Then it will provide some [additional React-specific rules](https://github.com/feross/eslint-config-standard-react/blob/0af445be5d1c83e1100ace159fd016838960d958/eslintrc.json#L19-L30). But honestly, you're much better off just using `standard` directly and skipping the process of configuring ESLint by hand.

It looks you're already using the `standard` command line program instead of `eslint` in the issue you linked. So, feel free to ignore this repo entirely.
