### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by lourenci** [feross/eslint-config-standard-react#50]
Dump question here:

I already have `standard` in my project, it works perfectly.
I have done the setup in `readme.md` to configure some rules for React, but this doesn't work.

What do I have to do?
I am calling the standard (`yarn standard`) in the same way that before.

**Comment by feross** [comment]
This eslint config isn't really meant to be used with the `standard` tool. It's only for users who are making their own .eslintrc file.

So you need to uninstall `standard`, then install `eslint` and put all your rules into an `.eslintrc` file. You're dropping down a level to use ESLint directly instead of the simple interface that the `standard` CLI provides.
