### ISSUE TITLE
no-did-update-set-state should not throw an error since React 16.4

### ISSUE THREAD

**Issue by barroudjo** [feross/eslint-config-standard-react#53]
Since componentWillReceiveProps has been deprecated, componentDidUpdate has to be used to detect changes in props and set state accordingly (the other option being using getDerivedStateFromProps AND polluting the state with old props just to track changes).

However I realise this is a bit tricky as it depends on the version of React...

**Comment by feross** [comment]
If you're relaxing a rule in order to support a pattern in the latest version of React, that seems fine to me. Can you send a pull request so we can look at what exactly would change here?

![mickey-wizard](https://user-images.githubusercontent.com/121766/62907205-e7fc7680-bd26-11e9-83f3-9614f069b5e0.gif)

**Comment by LinusU** [comment]
Closing since it hasn't been anything happening for a few years, happy to reopen if someone wants to work on this...
