### ISSUE TITLE
The Curious Case of the Dangling Comma

### ISSUE THREAD

**Issue by GantMan** [feross/eslint-config-standard-react#7]
I'm interested in using your library, and though I know it's not up for debate, I do seek a footnote on your reasoning to keep the `comma-dangle` rule in standard-react.   

I know [IE 8 is the culprit](http://eslint.org/docs/rules/no-comma-dangle.html) and I'm not even going to debate the scarcity of such a terrible browser.  

What I'm interested in, is would you consider at the very least, creating a version of standard-react that is primarily for react-native.  A safe place, where IE 8 can never go, and the friendliness of ECMA Script 5's dangling comma can come out and join the land of good ideas.

Poetic/Comma Deprived license aside, I'm interested in your feedback and thoughts on making Standard available for best practices in React Native.

**Comment by feross** [comment]
Hey @GantMan, thanks for your thoughtful issue!

The reason that we keep the comma-dangle rule, even in this config which appears to be specific to react, is that this config is actually used in the main `standard` tool. We ship one tool and need to decide on one set of rules. If you're doing a React Native project and want to change this rule you can look into extending standard using [eslint shareable configs](http://eslint.org/docs/developer-guide/shareable-configs.html).

Even when IE8 marketshare dwindles, we probably won't change this rule because so many people depend on `standard` and it's not fair to make them change their code because our preferences may have changed.

**Comment by dcousens** [comment]
@feross it could be worthwhile when we make the breaking change of assuming everyone is on ES6.

**Comment by feross** [comment]
Perhaps. But the formatter needs to be able to automatically fix people's code if we make a rule change. And right now the formatter is pretty bad at handling ES6.

**Comment by dcousens** [comment]
Indeed,  but I suspect this is all a ways off.

**Comment by feross** [comment]
Yep, agreed.

**Comment by GantMan** [comment]
Thanks for insight!  I'll make peace with the dangle-comma (for now :+1:  ) heh.

Cheers!
